persona_weights:
  single_clear: 150.0
  double_clear: 350.0
  triple_clear: 750.0
  tetris_clear: 1200.0
  game_over: -2000.0
  survival: 2.0
  piece_placed: 8.0
  hole_created: -60.0
  hole_filled: 25.0
  height_increase: -15.0
  height_decrease: 20.0
  bumpiness_increase: -10.0
  bumpiness_decrease: 8.0
  well_created: -20.0
  well_filled: 10.0
  line_setup: 12.0
  tetris_setup: 5.0
  combo_bonus: 40.0
  efficiency: 3.0
  height_danger_threshold: 0.5
  danger_penalty: -40.0
  invalid_action: -5.0
  waste_movement: -2.0
  low_placement: 5.0
  coverage: 4.0