persona_weights:
  win_bonus: 100.0
  loss_penalty: -50.0
  guess_penalty_base: -2.0
  info_gain_reward: 5.0
  letter_discovery: 3.0
  position_discovery: 2.0
  repeated_guess_penalty: -15.0
  invalid_guess_penalty: -20.0
  diversity_bonus: 2.0
  efficiency_multiplier: 1.2
  progress_reward: 1.0